[nats]
url = "nats://localhost:4222"
client = "serial-client"
cluster = "tele-cluster"

[subscription]
topic = "Telegram.Serial"
queue = "tele-queue"

[timeouts]
server = "5s"
reconnect_wait = "5s"
close = "10s"
ack_wait = "5s"

[hasura]
endpoint = "http://localhost:8080/v1/graphql"
secret  = "aviation-test"