apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus-dev
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true

  - name: Jaeger
    uid: jaeger-dev
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true

